services:
  vault:
    image: vault:1.13.3
    container_name: vault
    hostname: local.vault.docker
    restart: on-failure
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    command: vault server -config=/vault/config/vault.hcl
    volumes:
      - ./vault/data:/vault/data
      - ./vault/config:/vault/config
    networks:
      cv_network:
        ipv4_address: 172.0.0.10

  redis:
    image: redis:latest
    container_name: redis
    hostname: local.redis.docker
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    environment:
      REDIS_PASSWORD: $REDIS_PASSWORD
    networks:
      cv_network:
        ipv4_address: 172.0.0.11
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    hostname: local.redis-commander.docker
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local.redis.docker:local.redis.docker:6379:0:$REDIS_PASSWORD
    ports:
      - "6380:8081"
    networks:
      cv_network:
        ipv4_address: 172.0.0.12

  mysql:
    image: mysql:8.0.41
    container_name: mysql
    hostname: local.mysql.docker
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      cv_network:
        ipv4_address: 172.0.0.13
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    hostname: local.zookeeper.docker
    restart: unless-stopped
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      cv_network:
        ipv4_address: 172.0.0.14

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: local.kafka.docker
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: local.zookeeper.docker:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      cv_network:
        ipv4_address: 172.0.0.15

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    hostname: local.kafka-ui.docker
    restart: unless-stopped
    ports:
      - 8070:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: CV-DEV
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    networks:
      cv_network:
        ipv4_address: 172.0.0.16

networks:
  cv_network:
    name: cv_network
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/24
