services:
  service-registry:
    image: ghcr.io/creatorsventure/s01-service-registry:latest
    container_name: service-registry
    hostname: local.service-registry.docker
    restart: unless-stopped
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./service-registry/config:/app/config
    networks:
      cv_network:
        ipv4_address: 172.0.0.50

  cloud-config:
    image: ghcr.io/creatorsventure/s02-cloud-config:latest
    container_name: cloud-config
    hostname: local.cloud-config.docker
    restart: unless-stopped
    depends_on:
      - service-registry
    ports:
      - "8081:8081"
    environment:
      VAULT_URI: http://local.vault.docker:8200
      VAULT_HOSTNAME: local.vault.docker
      VAULT_TOKEN: $VAULT_TOKEN
      SPRING_PROFILES_ACTIVE: git,vault,dev
    volumes:
      - ./cloud-config/config:/app/config
    networks:
      cv_network:
        ipv4_address: 172.0.0.51

networks:
  cv_network:
    external: true
