services:
  cloud-gateway:
    image: ghcr.io/creatorsventure/s03-cloud-gateway:latest
    container_name: cloud-gateway
    hostname: local.cloud-gateway.docker
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CONFIG_SERVER_URL: configserver:http://local.cloud-config.docker:8081
    volumes:
      - ./cloud-gateway/config:/app/config
    networks:
      cv_network:
        ipv4_address: 172.0.0.101

  notify-service:
    image: ghcr.io/creatorsventure/s04-04-notify-service:latest
    container_name: notify-service
    hostname: local.notify-service.docker
    restart: unless-stopped
    ports:
      - "8010:8010"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      CONFIG_SERVER_URL: configserver:http://local.cloud-config.docker:8081
    volumes:
      - ./notify-service/config:/app/config
    networks:
      cv_network:
        ipv4_address: 172.0.0.102

networks:
  cv_network:
    external: true
