services:
  cloud-gateway:
    image: ghcr.io/creatorsventure/s03-cloud-gateway:latest
    container_name: cloud-gateway
    hostname: local.cloud-gateway.docker
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      CONFIG_SERVER_URL: configserver:http://local.cloud-config.docker:8081
    volumes:
      - ./cloud-gateway/config:/app/config
    networks:
      cv_network:
        ipv4_address: 172.0.0.18

networks:
  cv_network:
    external: true
